-- =====================================================================
-- SmartSched AI — Seed Data (local development / demo)
-- Matches the scenario shown in the product wireframes:
-- Prof. John Smith teaching DBMS/AI to TY-A, TY-B, SY-C.
-- =====================================================================

USE smartsched_ai;

SET FOREIGN_KEY_CHECKS = 0;

-- Departments
INSERT INTO departments (name, code) VALUES
  ('Computer Engineering', 'COMP'),
  ('Information Technology', 'IT');

-- Academic Years
INSERT INTO academic_years (name, year_order) VALUES
  ('FY', 1), ('SY', 2), ('SEDA', 3), ('TY', 4), ('Final Year', 5);

-- Divisions
INSERT INTO divisions (academic_year_id, department_id, name, strength, is_online) VALUES
  ((SELECT academic_year_id FROM academic_years WHERE name='TY'), 1, 'A', 65, FALSE),
  ((SELECT academic_year_id FROM academic_years WHERE name='TY'), 1, 'B', 63, FALSE),
  ((SELECT academic_year_id FROM academic_years WHERE name='SY'), 1, 'C', 60, FALSE),
  ((SELECT academic_year_id FROM academic_years WHERE name='SEDA'), 1, 'A', 45, FALSE),
  ((SELECT academic_year_id FROM academic_years WHERE name='Final Year'), 1, 'A', 58, TRUE);

-- Every division has three lab/tutorial batches. Strengths are split as
-- evenly as possible, with any remainder assigned to earlier batches.
INSERT INTO batches (division_id, name, strength)
SELECT division_id, 'B1', CEILING(COALESCE(strength, 0) / 3) FROM divisions
UNION ALL
SELECT division_id, 'B2', CEILING((COALESCE(strength, 0) - CEILING(COALESCE(strength, 0) / 3)) / 2) FROM divisions
UNION ALL
SELECT division_id, 'B3', COALESCE(strength, 0) - CEILING(COALESCE(strength, 0) / 3)
  - CEILING((COALESCE(strength, 0) - CEILING(COALESCE(strength, 0) / 3)) / 2) FROM divisions;

-- Users (1 admin, 2 faculty) — password_hash values are bcrypt placeholders;
-- real hashes are generated by the FastAPI auth service in Phase 3.
INSERT INTO users (name, email, password_hash, role) VALUES
  ('HOD Admin', 'admin@college.edu', '$2b$12$placeholderplaceholderplaceholderplaceh', 'admin'),
  ('Prof. John Smith', 'jsmith@college.edu', '$2b$12$placeholderplaceholderplaceholderplaceh', 'faculty'),
  ('Prof. Anita Rao', 'arao@college.edu', '$2b$12$placeholderplaceholderplaceholderplaceh', 'faculty');

-- Faculty profiles
INSERT INTO faculty (user_id, department_id, designation, max_weekly_hours) VALUES
  ((SELECT user_id FROM users WHERE email='jsmith@college.edu'), 1, 'Associate Professor', 18),
  ((SELECT user_id FROM users WHERE email='arao@college.edu'), 1, 'Assistant Professor', 16);

-- Subjects
INSERT INTO subjects (name, code, academic_year_id, department_id, credits, lectures_per_week, tutorials_per_week, lab_hours_per_week, is_online) VALUES
  ('Database Management Systems', 'CS301', (SELECT academic_year_id FROM academic_years WHERE name='TY'), 1, 4, 3, 1, 2, FALSE),
  ('Artificial Intelligence', 'CS302', (SELECT academic_year_id FROM academic_years WHERE name='SY'), 1, 4, 3, 0, 2, FALSE);

-- Subject-Faculty-Division assignments
INSERT INTO subject_faculty_assignment (subject_id, faculty_id, division_id, batch_id, delivery_type, academic_term) VALUES
  ((SELECT subject_id FROM subjects WHERE code='CS301'),
   (SELECT faculty_id FROM faculty WHERE user_id=(SELECT user_id FROM users WHERE email='jsmith@college.edu')),
   (SELECT division_id FROM divisions WHERE name='A' AND academic_year_id=(SELECT academic_year_id FROM academic_years WHERE name='TY')),
   NULL, 'theory', '2026-ODD'),
  ((SELECT subject_id FROM subjects WHERE code='CS302'),
   (SELECT faculty_id FROM faculty WHERE user_id=(SELECT user_id FROM users WHERE email='jsmith@college.edu')),
   (SELECT division_id FROM divisions WHERE name='C' AND academic_year_id=(SELECT academic_year_id FROM academic_years WHERE name='SY')),
   NULL, 'theory', '2026-ODD');

-- Rooms
INSERT INTO rooms (name, building, capacity, room_type) VALUES
  ('C-304', 'C Block', 70, 'classroom'),
  ('B-205', 'B Block', 60, 'classroom'),
  ('Lab-3', 'C Block', 30, 'laboratory'),
  ('T-101', 'C Block', 30, 'tutorial');

-- Time slots (Mon-Sat, 08:00–18:00 incl. lunch) — Monday shown fully;
-- other days are filled by backend/app/scheduling/time_slot_seeder.py.
INSERT INTO time_slots (day_of_week, start_time, end_time, slot_order, is_break) VALUES
  ('Monday', '08:00:00', '09:00:00', 1, FALSE),
  ('Monday', '09:00:00', '10:00:00', 2, FALSE),
  ('Monday', '10:00:00', '11:00:00', 3, FALSE),
  ('Monday', '11:00:00', '12:00:00', 4, FALSE),
  ('Monday', '12:00:00', '13:00:00', 5, TRUE),
  ('Monday', '13:00:00', '14:00:00', 6, FALSE),
  ('Monday', '14:00:00', '15:00:00', 7, FALSE),
  ('Monday', '15:00:00', '16:00:00', 8, FALSE),
  ('Monday', '16:00:00', '17:00:00', 9, FALSE),
  ('Monday', '17:00:00', '18:00:00', 10, FALSE);

-- Sample notifications
INSERT INTO notifications (user_id, title, detail) VALUES
  ((SELECT user_id FROM users WHERE email='jsmith@college.edu'), 'Extra DBMS Lecture Approved', 'Thursday 2-3 PM, Room C-304'),
  ((SELECT user_id FROM users WHERE email='jsmith@college.edu'), 'Friday Timetable Updated', NULL);

SET FOREIGN_KEY_CHECKS = 1;
